DROP TABLE IF EXISTS CONVERSIONS_LOG;
 
CREATE TABLE CONVERSIONS_LOG (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  SOURCE_AMOUNT DECIMAL(20,2),
  SOURCE_CURRENCY VARCHAR(3),
  TARGET_CURRENCY VARCHAR(3),
  TARGET_AMOUNT DECIMAL(20,2),
  TRANSACTION_ID VARCHAR(250),
  TRANSACTION_DATE DATE
);