
DROP TABLE IF EXISTS AIRLINE_COMPANY;
  
CREATE TABLE AIRLINE_COMPANY (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS AIRPORT;

CREATE TABLE AIRPORT (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS ROUTE;

CREATE TABLE ROUTE (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  DEPARTURE VARCHAR(250) NOT NULL,
  ARRIVAL VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS FLIGHT;

CREATE TABLE FLIGHT (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  FLIGHT_DATE DATE NOT NULL,
  TOTAL_QUOTA INT NOT NULL,
  TICKETS_SOLD INT NOT NULL,
  PRICE INT NOT NULL,
  CANCEL_FLAG INT NOT NULL,
  AIRPORT_ID INT NOT NULL,
  AIRLINE_COMPANY_ID INT NOT NULL,
  ROUTE_ID INT NOT NULL
);

DROP TABLE IF EXISTS TICKET;

CREATE TABLE TICKET (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  TICKET_NUMBER VARCHAR(250) NOT NULL,
  TICKET_CLASS VARCHAR(250) NOT NULL,
  FLIGHT_ID INT NOT NULL, 
  CANCEL_FLAG INT NOT NULL
);