spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: test
    password: test
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true